--require("vim._core.ui2").enable({})

require("config.options")
require("config.keymaps")
require("config.autocmds")
require("pack")
require("sitter")
require("lsp")
require("line")
vim.cmd.colorscheme("vscode")
