local M = {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	event = "BufReadPost",
	dependencies = {
		"nvim-treesitter/nvim-treesitter-context",
		"nvim-treesitter/nvim-treesitter-refactor",
	},
	opts = {
		highlight = {
			enable = true,
			disable = function(_, buf)
				local max_filesize = 200 * 1024 -- 100 KB
				local ok, stats =
					pcall(vim.uv.fs_stat, vim.api.nvim_buf_get_name(buf))
				if ok and stats and stats.size > max_filesize then
					return true
				end
			end,
			additional_vim_regex_highlighting = false,
		},
		autopairs = { enable = true },
		autotag = { enable = true },
		indent = { enable = true },
		ensure_installed = {
			"asm",
			"awk",
			"bash",
			"bibtex",
			"c",
			"clojure",
			"cmake",
			"comment",
			"cpp",
			"css",
			"csv",
			"diff",
			"disassembly",
			"dockerfile",
			"doxygen",
			"editorconfig",
			"fish",
			"fortran",
			"git_config",
			"git_rebase",
			"gitattributes",
			"gitcommit",
			"gitignore",
			"gn",
			"gnuplot",
			"go",
			"gomod",
			"gpg",
			"haskell",
			"html",
			"htmldjango",
			"http",
			"ini",
			"javascript",
			"jinja",
			"jinja_inline",
			"jsdoc",
			"json",
			"json5",
			"jsonc",
			"jq",
			"just",
			"kdl",
			"latex",
			"linkerscript",
			"llvm",
			"lua",
			"luadoc",
			"luap",
			"make",
			"markdown",
			"markdown_inline",
			"mermaid",
			"meson",
			"ninja",
			"pem",
			"perl",
			"php",
			"phpdoc",
			"powershell",
			"printf",
			"psv",
			"pymanifest",
			"python",
			"query",
			"readline",
			"regex",
			"requirements",
			"rst",
			"ruby",
			"rust",
			"scss",
			"ssh_config",
			"teal",
			"textproto",
			"tmux",
			"todotxt",
			"toml",
			"tsv",
			"tsx",
			"typescript",
			"typst",
			"vim",
			"vimdoc",
			"xml",
			"yaml",
			"zathurarc",
			"zig",
		},
		sync_install = false,
		auto_install = true,
		ignore_install = {}, -- List of parsers to ignore installation
		refactor = {
			highlight_definitions = {
				enable = true,
				-- Set to false if you have an `updatetime` of ~100.
				clear_on_cursor_move = true,
			},
			highlight_current_scope = { enable = false },
		},
	},
	config = function(_, opts)
		require("nvim-treesitter.configs").setup(opts)
	end,
}

return M
